In [1]:
%config IPCompleter.greedy=True
import pandas as pd
df = pd.read_csv("testdata_exjobb.csv", encoding='ISO-8859-1')
df

caseid                                           FreeText  Age  Gender  \
0        1  Äng genom annan olika färdväg kan som sjö där ...   83       0   
1        2  Gör samma vad sin mjuka häst dimmhöljd när hel...   86       0   
2        3  Har rot bland stora precis upprätthållande oss...   73       0   
3        4  På bland häst regn annan del för bäckasiner si...   72       0   
4        5  Så lax ordningens mjuka där vidsträckt från tr...   44       1   
5        6  På flera gör vemod sig bra denna miljoner, ser...   68       1   
6        7  Hans rännil tid därmed blev regn vad söka bäck...   74       0   
7        8  Björnbär söka gör sjö för kan annan det, som p...   42       0   
8        9  Sjö själv häst ta annan faktor blivit ser rot ...   81       0   
9       10  Ta erfarenheter i är stora del sista som, när ...   40       0   
10      11  Brunsås olika verkligen icke träutensilierna j...   25       0   
11      12  Helt kom annat samtidigt där flera enligt inom...   81       1   
12      13  Vad söka vemod smultron sista genom söka upprä...   23       1   
13      14  Groda kanske erfarenheter sorgliga björnbär på...   74       0   
14      15  Precis och vidsträckt erfarenheter vemod hans ...   56       0   
15      16  Som tidigare sax ser lax gör tid erfarenheter ...   63       1   
16      17  Lax varit brunsås vemod hav mjuka faktor tre s...   96       0   
17      18  Bra sitt plats dimma sax kunde när groda samma...   29       0   
18      19  Plats av bäckasiner vidsträckt som sig hans, s...   30       1   

    LastContactN  LastContactDays  operator      pout  prio  hosp_ed  ...  \
0              0          31.0000         6        2A     2        0  ...   
1              0          31.0000         5        2A     2        1  ...   
2              0          31.0000         6        2B     1        0  ...   
3              0          31.0000         5        2A     2        1  ...   
4              1           1.4520         2        2B     1        1  ...   
5              0          31.0000         6  Referral     0        0  ...   
6              0          31.0000         5        2A     2        1  ...   
7              0          31.0000         5        2A     2        1  ...   
8              0          31.0000         6        2A     2        1  ...   
9              0          31.0000         5  Referral     0        0  ...   
10             1           5.2452         5        2A     2        1  ...   
11             0          31.0000         6        2A     2        1  ...   
12             0          31.0000         6        2B     1        0  ...   
13             0          31.0000         5        2A     2        0  ...   
14             0          31.0000         3        1A     4        1  ...   
15             1          31.0000         3        2B     1        1  ...   
16             0          31.0000         3        1B     3        1  ...   
17             0          31.0000         3  Referral     0        0  ...   
18             0          31.0000         3        2A     2        1  ...   

    9d2b7edb-e3c1-4c83-885c-92750baa1bf6_9d2b7edb-e3c1-4c83-885c-92750baa1bf6  \
0                                                   0                           
1                                                   0                           
2                                                   0                           
3                                                   0                           
4                                                   0                           
5                                                   0                           
6                                                   0                           
7                                                   0                           
8                                                   0                           
9                                                   0                           
10         

In [2]:
#dummies = pd.get_dummies(df.FreeText)
dummies = df.iloc[:,0:2]
dummies.values

array([[1,
        'Äng genom annan olika färdväg kan som sjö där äng, det bland samtidigt groda genom sig träutensilierna faktor. Miljoner har rännil kunde annat blivit helt mjuka kunde sjö och, träutensilierna är mot fram ta flera där om.'],
       [2,
        'Gör samma vad sin mjuka häst dimmhöljd när helt träutensilierna rot, flera hans söka del ordningens varit hela strand sig, redan tid sällan omfångsrik nu kom olika ordningens så. Denna vid sjö är det nu hwila sin sista tidigare omfångsrik, bra björnbär blivit ta åker göras tidigare kanske. Ingalunda plats samma det hwila del som själv mot, sorgliga hans annat där upprätthållande därmed enligt kunde, trevnadens erfarenheter där stora upprätthållande och sista.'],
       [3,
        'Har rot bland stora precis upprätthållande oss trevnadens, äng oss sjö fram åker dunge år, jäst dimmhöljd gamla faktor smultron nu. Samtidigt sin år och annan kunde björnbär, sista inom och hela träutensilierna, plats stora brunsås björnbär tidigare

In [3]:
import re
sentence = [None] * df.shape[0]
for i in range(len(sentence)):
    old_sentence = dummies.iloc[i].FreeText
    word = list(old_sentence.split())
    words = [None] * len(word)
    for i in range(len(word)):
        words[i] = re.sub('(?<=\D)[.,]|[.,](?=\D)', '', word[i].lower())
    words1 = [x for x in words if x is not None]
    sentence.append(' '.join(words1))
    sentence1 = [x for x in sentence if x is not None]
df['newFreeText'] = [str(x) for x in sentence1]
df

caseid                                           FreeText  Age  Gender  \
0        1  Äng genom annan olika färdväg kan som sjö där ...   83       0   
1        2  Gör samma vad sin mjuka häst dimmhöljd när hel...   86       0   
2        3  Har rot bland stora precis upprätthållande oss...   73       0   
3        4  På bland häst regn annan del för bäckasiner si...   72       0   
4        5  Så lax ordningens mjuka där vidsträckt från tr...   44       1   
5        6  På flera gör vemod sig bra denna miljoner, ser...   68       1   
6        7  Hans rännil tid därmed blev regn vad söka bäck...   74       0   
7        8  Björnbär söka gör sjö för kan annan det, som p...   42       0   
8        9  Sjö själv häst ta annan faktor blivit ser rot ...   81       0   
9       10  Ta erfarenheter i är stora del sista som, när ...   40       0   
10      11  Brunsås olika verkligen icke träutensilierna j...   25       0   
11      12  Helt kom annat samtidigt där flera enligt inom...   81       1   
12      13  Vad söka vemod smultron sista genom söka upprä...   23       1   
13      14  Groda kanske erfarenheter sorgliga björnbär på...   74       0   
14      15  Precis och vidsträckt erfarenheter vemod hans ...   56       0   
15      16  Som tidigare sax ser lax gör tid erfarenheter ...   63       1   
16      17  Lax varit brunsås vemod hav mjuka faktor tre s...   96       0   
17      18  Bra sitt plats dimma sax kunde när groda samma...   29       0   
18      19  Plats av bäckasiner vidsträckt som sig hans, s...   30       1   

    LastContactN  LastContactDays  operator      pout  prio  hosp_ed  ...  \
0              0          31.0000         6        2A     2        0  ...   
1              0          31.0000         5        2A     2        1  ...   
2              0          31.0000         6        2B     1        0  ...   
3              0          31.0000         5        2A     2        1  ...   
4              1           1.4520         2        2B     1        1  ...   
5              0          31.0000         6  Referral     0        0  ...   
6              0          31.0000         5        2A     2        1  ...   
7              0          31.0000         5        2A     2        1  ...   
8              0          31.0000         6        2A     2        1  ...   
9              0          31.0000         5  Referral     0        0  ...   
10             1           5.2452         5        2A     2        1  ...   
11             0          31.0000         6        2A     2        1  ...   
12             0          31.0000         6        2B     1        0  ...   
13             0          31.0000         5        2A     2        0  ...   
14             0          31.0000         3        1A     4        1  ...   
15             1          31.0000         3        2B     1        1  ...   
16             0          31.0000         3        1B     3        1  ...   
17             0          31.0000         3  Referral     0        0  ...   
18             0          31.0000         3        2A     2        1  ...   

    ac29a321-8fea-4b0f-b2dd-7d4d6b16fc7d_ac29a321-8fea-4b0f-b2dd-7d4d6b16fc7d  \
0                                                   0                           
1                                                   0                           
2                                                   0                           
3                                                   0                           
4                                                   0                           
5                                                   0                           
6                                                   0                           
7                                                   0                           
8                                                   0                           
9                                                   0                           
10         

In [4]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from numpy import argmax
values = array(sentence1)
values[0]

'äng genom annan olika färdväg kan som sjö där äng det bland samtidigt groda genom sig träutensilierna faktor miljoner har rännil kunde annat blivit helt mjuka kunde sjö och träutensilierna är mot fram ta flera där om'

In [5]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

[18  4  6 11 15 12  5  0 13 16  2  7 17  3 10 14  8  1  9]


In [6]:
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
onehot_encoded

/home/dimitriuu/.local/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [7]:
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
inverted

array(['äng genom annan olika färdväg kan som sjö där äng det bland samtidigt groda genom sig träutensilierna faktor miljoner har rännil kunde annat blivit helt mjuka kunde sjö och träutensilierna är mot fram ta flera där om'],
      dtype='<U455')

In [8]:
X_train, X_test, y_train, y_test = train_test_split(onehot_encoded, df.pout, test_size=0.3)
X_train

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.

In [9]:
X_test

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0.]])

In [10]:
y_train

12          2B
14          1A
8           2A
2           2B
15          2B
17    Referral
7           2A
4           2B
3           2A
0           2A
16          1B
9     Referral
10          2A
Name: pout, dtype: object

In [11]:
y_test

18          2A
13          2A
11          2A
6           2A
1           2A
5     Referral
Name: pout, dtype: object

In [12]:
model = LogisticRegression()
model.fit(X_train,y_train)

/home/dimitriuu/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/dimitriuu/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [13]:
model.predict(X_test)

array(['2A', '2A', '2A', '2A', '2A', '2A'], dtype=object)

In [14]:
model.score(X_test,y_test)

0.8333333333333334

In [15]:
X_train, X_test, y_train, y_test = train_test_split(onehot_encoded, df.pout.values, test_size=0.3)

In [16]:
import fastText

In [17]:
from pyfasttext import FastText

In [18]:
model = FastText()

In [25]:
train = []

dummies.to_csv('fast.txt', index=False, header=None)
model.skipgram(input='fast.txt', output='model', epoch=100, lr=0.7)

In [26]:
for word in model.words:
    print(word, model[word])

</s> array('f', [83.82762908935547, -195.16836547851562, 104.38960266113281, 46.70646286010742, 128.36703491210938, 62.95054244995117, -158.69923400878906, -149.38230895996094, -155.7270965576172, -1.8243489265441895, -79.35702514648438, -74.64189147949219, -118.44384002685547, -132.77362060546875, 139.25784301757812, 13.881562232971191, -123.04707336425781, 3.324237585067749, -71.3295669555664, 22.57051658630371, 63.189125061035156, 39.218875885009766, -153.46302795410156, 16.754451751708984, -90.80558013916016, 46.10792541503906, 19.864768981933594, -29.39786720275879, 42.84381103515625, -50.499122619628906, 52.2254753112793, -52.97343444824219, 68.41998291015625, 105.68724060058594, 99.85350799560547, 15.456881523132324, -63.73336410522461, -34.74822998046875, 112.93436431884766, -107.90455627441406, -78.68611907958984, 112.16918182373047, -27.585615158081055, 90.13432312011719, -38.55378723144531, 1.4552040100097656, 24.87447738647461, 9.549636840820312, -62.36982345581055, 119.221

In [27]:
model.numpy_normalized_vectors.shape

(78, 100)

In [28]:
model.nwords

78

In [45]:
X = model.numpy_normalized_vectors
X.shape

(78, 100)

In [66]:
X_train, X_test, y_train, y_test = train_test_split(dummies.values, df.pout.values, test_size=0.3)

In [1]:
import numpy as np
