In [1]:
import pandas as pd
df = pd.read_csv("testdata_exjobb.csv", encoding='ISO-8859-1')
df

caseid                                           FreeText  Age  Gender  \
0        1  Äng genom annan olika färdväg kan som sjö där ...   83       0   
1        2  Gör samma vad sin mjuka häst dimmhöljd när hel...   86       0   
2        3  Har rot bland stora precis upprätthållande oss...   73       0   
3        4  På bland häst regn annan del för bäckasiner si...   72       0   
4        5  Så lax ordningens mjuka där vidsträckt från tr...   44       1   
5        6  På flera gör vemod sig bra denna miljoner, ser...   68       1   
6        7  Hans rännil tid därmed blev regn vad söka bäck...   74       0   
7        8  Björnbär söka gör sjö för kan annan det, som p...   42       0   
8        9  Sjö själv häst ta annan faktor blivit ser rot ...   81       0   
9       10  Ta erfarenheter i är stora del sista som, när ...   40       0   
10      11  Brunsås olika verkligen icke träutensilierna j...   25       0   
11      12  Helt kom annat samtidigt där flera enligt inom...   81       1   
12      13  Vad söka vemod smultron sista genom söka upprä...   23       1   
13      14  Groda kanske erfarenheter sorgliga björnbär på...   74       0   
14      15  Precis och vidsträckt erfarenheter vemod hans ...   56       0   
15      16  Som tidigare sax ser lax gör tid erfarenheter ...   63       1   
16      17  Lax varit brunsås vemod hav mjuka faktor tre s...   96       0   
17      18  Bra sitt plats dimma sax kunde när groda samma...   29       0   
18      19  Plats av bäckasiner vidsträckt som sig hans, s...   30       1   

    LastContactN  LastContactDays  operator      pout  prio  hosp_ed  ...  \
0              0          31.0000         6        2A     2        0  ...   
1              0          31.0000         5        2A     2        1  ...   
2              0          31.0000         6        2B     1        0  ...   
3              0          31.0000         5        2A     2        1  ...   
4              1           1.4520         2        2B     1        1  ...   
5              0          31.0000         6  Referral     0        0  ...   
6              0          31.0000         5        2A     2        1  ...   
7              0          31.0000         5        2A     2        1  ...   
8              0          31.0000         6        2A     2        1  ...   
9              0          31.0000         5  Referral     0        0  ...   
10             1           5.2452         5        2A     2        1  ...   
11             0          31.0000         6        2A     2        1  ...   
12             0          31.0000         6        2B     1        0  ...   
13             0          31.0000         5        2A     2        0  ...   
14             0          31.0000         3        1A     4        1  ...   
15             1          31.0000         3        2B     1        1  ...   
16             0          31.0000         3        1B     3        1  ...   
17             0          31.0000         3  Referral     0        0  ...   
18             0          31.0000         3        2A     2        1  ...   

    9d2b7edb-e3c1-4c83-885c-92750baa1bf6_9d2b7edb-e3c1-4c83-885c-92750baa1bf6  \
0                                                   0                           
1                                                   0                           
2                                                   0                           
3                                                   0                           
4                                                   0                           
5                                                   0                           
6                                                   0                           
7                                                   0                           
8                                                   0                           
9                                                   0                           
10         

In [2]:
#dummies = pd.get_dummies(df.FreeText)
dummies = df.iloc[:,0:2]
dummies

caseid                                           FreeText
0        1  Äng genom annan olika färdväg kan som sjö där ...
1        2  Gör samma vad sin mjuka häst dimmhöljd när hel...
2        3  Har rot bland stora precis upprätthållande oss...
3        4  På bland häst regn annan del för bäckasiner si...
4        5  Så lax ordningens mjuka där vidsträckt från tr...
5        6  På flera gör vemod sig bra denna miljoner, ser...
6        7  Hans rännil tid därmed blev regn vad söka bäck...
7        8  Björnbär söka gör sjö för kan annan det, som p...
8        9  Sjö själv häst ta annan faktor blivit ser rot ...
9       10  Ta erfarenheter i är stora del sista som, när ...
10      11  Brunsås olika verkligen icke träutensilierna j...
11      12  Helt kom annat samtidigt där flera enligt inom...
12      13  Vad söka vemod smultron sista genom söka upprä...
13      14  Groda kanske erfarenheter sorgliga björnbär på...
14      15  Precis och vidsträckt erfarenheter vemod hans ...
15      16  Som tidigare sax ser lax gör tid erfarenheter ...
16      17  Lax varit brunsås vemod hav mjuka faktor tre s...
17      18  Bra sitt plats dimma sax kunde när groda samma...
18      19  Plats av bäckasiner vidsträckt som sig hans, s...

In [3]:
import re
sentence = [None] * df.shape[0]
for i in range(len(sentence)):
    old_sentence = dummies.iloc[i].FreeText
    word = list(old_sentence.split())
    words = [None] * len(word)
    for i in range(len(word)):
        words[i] = re.sub('(?<=\D)[.,]|[.,](?=\D)', '', word[i].lower())
    words1 = [x for x in words if x is not None]
    sentence.append(' '.join(words1))
    sentence1 = [x for x in sentence if x is not None]
df['newFreeText'] = [str(x) for x in sentence1]
df

caseid                                           FreeText  Age  Gender  \
0        1  Äng genom annan olika färdväg kan som sjö där ...   83       0   
1        2  Gör samma vad sin mjuka häst dimmhöljd när hel...   86       0   
2        3  Har rot bland stora precis upprätthållande oss...   73       0   
3        4  På bland häst regn annan del för bäckasiner si...   72       0   
4        5  Så lax ordningens mjuka där vidsträckt från tr...   44       1   
5        6  På flera gör vemod sig bra denna miljoner, ser...   68       1   
6        7  Hans rännil tid därmed blev regn vad söka bäck...   74       0   
7        8  Björnbär söka gör sjö för kan annan det, som p...   42       0   
8        9  Sjö själv häst ta annan faktor blivit ser rot ...   81       0   
9       10  Ta erfarenheter i är stora del sista som, när ...   40       0   
10      11  Brunsås olika verkligen icke träutensilierna j...   25       0   
11      12  Helt kom annat samtidigt där flera enligt inom...   81       1   
12      13  Vad söka vemod smultron sista genom söka upprä...   23       1   
13      14  Groda kanske erfarenheter sorgliga björnbär på...   74       0   
14      15  Precis och vidsträckt erfarenheter vemod hans ...   56       0   
15      16  Som tidigare sax ser lax gör tid erfarenheter ...   63       1   
16      17  Lax varit brunsås vemod hav mjuka faktor tre s...   96       0   
17      18  Bra sitt plats dimma sax kunde när groda samma...   29       0   
18      19  Plats av bäckasiner vidsträckt som sig hans, s...   30       1   

    LastContactN  LastContactDays  operator      pout  prio  hosp_ed  ...  \
0              0          31.0000         6        2A     2        0  ...   
1              0          31.0000         5        2A     2        1  ...   
2              0          31.0000         6        2B     1        0  ...   
3              0          31.0000         5        2A     2        1  ...   
4              1           1.4520         2        2B     1        1  ...   
5              0          31.0000         6  Referral     0        0  ...   
6              0          31.0000         5        2A     2        1  ...   
7              0          31.0000         5        2A     2        1  ...   
8              0          31.0000         6        2A     2        1  ...   
9              0          31.0000         5  Referral     0        0  ...   
10             1           5.2452         5        2A     2        1  ...   
11             0          31.0000         6        2A     2        1  ...   
12             0          31.0000         6        2B     1        0  ...   
13             0          31.0000         5        2A     2        0  ...   
14             0          31.0000         3        1A     4        1  ...   
15             1          31.0000         3        2B     1        1  ...   
16             0          31.0000         3        1B     3        1  ...   
17             0          31.0000         3  Referral     0        0  ...   
18             0          31.0000         3        2A     2        1  ...   

    ac29a321-8fea-4b0f-b2dd-7d4d6b16fc7d_ac29a321-8fea-4b0f-b2dd-7d4d6b16fc7d  \
0                                                   0                           
1                                                   0                           
2                                                   0                           
3                                                   0                           
4                                                   0                           
5                                                   0                           
6                                                   0                           
7                                                   0                           
8                                                   0                           
9                                                   0                           
10         

In [21]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from numpy import argmax
values = array(sentence1)
values[0]

'äng genom annan olika färdväg kan som sjö där äng det bland samtidigt groda genom sig träutensilierna faktor miljoner har rännil kunde annat blivit helt mjuka kunde sjö och träutensilierna är mot fram ta flera där om'

In [22]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

[18  4  6 11 15 12  5  0 13 16  2  7 17  3 10 14  8  1  9]


In [23]:
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
onehot_encoded

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [24]:
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
inverted

array(['äng genom annan olika färdväg kan som sjö där äng det bland samtidigt groda genom sig träutensilierna faktor miljoner har rännil kunde annat blivit helt mjuka kunde sjö och träutensilierna är mot fram ta flera där om'],
      dtype='<U455')

In [26]:
X_train, X_test, y_train, y_test = train_test_split(onehot_encoded, df.pout, test_size=0.3)
X_train

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [27]:
X_test

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]])

In [28]:
y_train

3           2A
6           2A
9     Referral
14          1A
5     Referral
18          2A
7           2A
2           2B
0           2A
12          2B
10          2A
1           2A
15          2B
Name: pout, dtype: object

In [29]:
y_test

4           2B
17    Referral
11          2A
8           2A
13          2A
16          1B
Name: pout, dtype: object

In [35]:
model = LogisticRegression()
model.fit(X_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [36]:
model.predict(X_test)

array(['2A', '2A', '2A', '2A', '2A', '2A'], dtype=object)

In [37]:
model.score(X_test,y_test)

0.5